### ISSUE TITLE
No module named pygame

### ISSUE THREAD

**Issue by tailintalent** [Raeon/pygar#11]
When I run the test.py, it shows the following error:

Traceback (most recent call last):
  File "E:/Project/ML/2-Projects/Agar.io/pygar-master/test.py", line 8, in <module>
    from viewer import GameViewer
  File "E:\Project\ML\2-Projects\Agar.io\pygar-master\viewer.py", line 3, in <module>
    import pygame
ImportError: No module named 'pygame'

Do you miss a module 'pygame'?

**Comment by dannycbc** [comment]
you have to download a extencion to python called pygame, its an easy
download just google it ;)
Em 12/07/2015 22:20, "tailintalent" <notifications@github.com> escreveu:
